import keyMirror from 'keymirror';

export default keyMirror({
    LOAD_USERS_REQUEST: null,
    LOAD_USERS_SUCCESS: null,
    LOAD_USERS_FAIL: null,
    LOAD_COMMENTS_REQUEST: null,
    LOAD_COMMENTS_SUCCESS: null,
    LOAD_COMMENTS_FAIL: null,
    LOAD_GROUPS_REQUEST: null,
    LOAD_GROUPS_SUCCESS: null,
    LOAD_GROUPS_FAIL: null,
    LOAD_CONNECTORS_REQUEST: null,
    LOAD_CONNECTORS_SUCCESS: null,
    LOAD_CONNECTORS_FAIL: null,
    CHECK_CONNECTORS_CONNECTION: null,
    CHECK_CONNECTORS_SUCCESS: null,
    CHECK_CONNECTORS_FAIL: null
});